In [1]:
#pip! install numpy

In [2]:
import numpy as np

In [3]:
np.sqrt(4)

2.0

In [4]:
arr = np.array([1,2,3,4,5])

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
arr_list = [1,2,3,4,5]

In [7]:
arr1 = np.array(arr_list)

In [8]:
arr1

array([1, 2, 3, 4, 5])

In [9]:
twoD_arr = np.array([[1,2,3],[4,5,6]])

In [10]:
twoD_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
twoD_arr.ndim

2

In [17]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [18]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [19]:
arr[1,0,1]

8

In [20]:
arr[1,0,1:3]

array([8, 9])

Using np.zeros to initialize a matrix. Or have array with zeroes
<br> np.zeros(shape)

In [30]:
arr = np.zeros((5,2,3))

In [31]:
arr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [33]:
arr1 = np.zeros(5)

In [34]:
arr1

array([0., 0., 0., 0., 0.])

In [36]:
for idx, x in np.ndenumerate(arr1):
    arr1[idx] = x+1

In [37]:
arr1

array([1., 1., 1., 1., 1.])

In [38]:
arr2 = np.array([1,2,3,4,5])

In [39]:
np.concatenate((arr1,arr2))

array([1., 1., 1., 1., 1., 1., 2., 3., 4., 5.])

In [41]:
np.stack((arr1,arr2), axis = 1)

array([[1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.],
       [1., 5.]])

In [43]:
np.vstack((arr1,arr2))

array([[1., 1., 1., 1., 1.],
       [1., 2., 3., 4., 5.]])